export type SectionDefinition = {
  id: string;
  pageNumber: number;
  navTitle: string;
  overlayName: string;
  overlayTitle: string;
  ariaLabel: string;
  monoLabel?: string;
  displayLine1?: string;
  displayLine2?: string;
};

export const SECTIONS: SectionDefinition[] = [
  {
    id: "cover",
    pageNumber: 1,
    navTitle: "Cover",
    overlayName: "Cover",
    overlayTitle: "A Voyage of the Senses.",
    ariaLabel: "Cover: Regent Seven Seas and M. Shanken, H2 2026",
    monoLabel: "H2 2026 · Digital Media Partnership · Deck Script",
    displayLine1: "A Voyage",
    displayLine2: "of the Senses.",
  },
  {
    id: "brief",
    pageNumber: 2,
    navTitle: "The Brief",
    overlayName: "The Brief",
    overlayTitle: "Reach, relevance, rhythm.",
    ariaLabel: "The Brief: reach, relevance, rhythm",
    monoLabel: "— THE BRIEF",
    displayLine1: "The Brief",
    displayLine2: "",
  },
  {
    id: "audience",
    pageNumber: 3,
    navTitle: "The Audience",
    overlayName: "The Audience",
    overlayTitle: "Affluent epicureans, already on board.",
    ariaLabel: "The Audience: demographics and footprint",
    monoLabel: "— THE AUDIENCE",
    displayLine1: "The Audience",
    displayLine2: "",
  },
  {
    id: "the-window",
    pageNumber: 4,
    navTitle: "The Window",
    overlayName: "The Window",
    overlayTitle: "A second-half campaign in seven movements.",
    ariaLabel: "The Window: seven movements from June through December",
    monoLabel: "— THE WINDOW",
    displayLine1: "The Window",
    displayLine2: "",
  },
  {
    id: "plan-inventory",
    pageNumber: 5,
    navTitle: "Plan Inventory",
    overlayName: "Plan Inventory",
    overlayTitle: "Fifteen placements, on the dates that fit the window.",
    ariaLabel: "Plan inventory: fifteen placements per proposal",
    monoLabel: "— PLAN INVENTORY · PER PROPOSAL · ADJUSTED DATES",
    displayLine1: "Plan Inventory",
    displayLine2: "",
  },
  {
    id: "the-program",
    pageNumber: 6,
    navTitle: "The Program",
    overlayName: "The Program",
    overlayTitle: "Three pillars, one season, one shared idea.",
    ariaLabel: "The Program: three pillars and creative architecture",
    monoLabel: "— THE PROGRAM",
    displayLine1: "The Program",
    displayLine2: "",
  },
  {
    id: "pillar-i",
    pageNumber: 7,
    navTitle: "Pillar I",
    overlayName: "Pillar I — Interactive Voyage Map",
    overlayTitle: "Always-On · Hub residency.",
    ariaLabel: "Pillar I: Interactive Voyage Map",
    monoLabel: "— PILLAR I",
    displayLine1: "Interactive Voyage Map.",
    displayLine2: "",
  },
  {
    id: "pillar-ii",
    pageNumber: 8,
    navTitle: "Pillar II",
    overlayName: "Pillar II — Rare Spirits, Rare Destinations",
    overlayTitle: "Long-form · Expert voices · Hub residency.",
    ariaLabel: "Pillar II: Rare Spirits, Rare Destinations three-part series",
    monoLabel: "— PILLAR II",
    displayLine1: "Rare Spirits, Rare Destinations.",
    displayLine2: "",
  },
  {
    id: "pillar-iii",
    pageNumber: 9,
    navTitle: "Pillar III",
    overlayName: "Pillar III — Dram Diaries with Jonny McCormack",
    overlayTitle: "13 social units · 5 weeks of post-voyage.",
    ariaLabel: "Pillar III: Dram Diaries with Jonny McCormack",
    monoLabel: "— PILLAR III",
    displayLine1: "Dram Diaries with Jonny McCormack.",
    displayLine2: "",
  },
  {
    id: "the-hub",
    pageNumber: 10,
    navTitle: "The Hub",
    overlayName: "The Hub",
    overlayTitle: "Always-On · the Home · Jun 15 → Dec 31 · 6.5 months",
    ariaLabel: "The Hub at Wine Spectator: sponsored hub for pillars",
    monoLabel: "— THE HUB",
    displayLine1: "The Hub",
    displayLine2: "",
  },
  {
    id: "june-launch",
    pageNumber: 11,
    navTitle: "June",
    overlayName: "June · New Season Launch",
    overlayTitle: "Movement i · Awaken · June 15–30 · 2026",
    ariaLabel: "June: New Season Launch",
    monoLabel: "— MOVEMENT I · AWAKEN · JUNE 15–30 · 2026",
    displayLine1: "New Season Launch.",
    displayLine2: "",
  },
  {
    id: "july-surge",
    pageNumber: 12,
    navTitle: "July",
    overlayName: "July · Mid-Year Surge + WC '29",
    overlayTitle: "Two flights, running in parallel.",
    ariaLabel: "July: Mid-Year Booking Surge and World Cruise 2029 sneak peek",
    monoLabel: "— MOVEMENT I · AWAKEN · JULY · 2026",
    displayLine1: "July",
    displayLine2: "",
  },
  {
    id: "august-prestige",
    pageNumber: 13,
    navTitle: "August",
    overlayName: "August · Prestige Winter Push",
    overlayTitle: "Prestige Winter Push.",
    ariaLabel: "August: Prestige Winter Push",
    monoLabel: "— MOVEMENT II · INDULGE · AUGUST · 2026",
    displayLine1: "Prestige Winter Push.",
    displayLine2: "",
  },
  {
    id: "september-whiskylive",
    pageNumber: 14,
    navTitle: "September",
    overlayName: "September · Whisky LIVE",
    overlayTitle: "Spotlight on Whisky LIVE.",
    ariaLabel: "September: Spotlight on Whisky LIVE",
    monoLabel: "— MOVEMENT II · INDULGE · SEPTEMBER · 2026",
    displayLine1: "Spotlight on Whisky LIVE.",
    displayLine2: "",
  },
  {
    id: "year-end-lists",
    pageNumber: 15,
    navTitle: "Nov/Dec",
    overlayName: "November · December — Year-End Lists",
    overlayTitle: "The year ends on the page the reader reads twice.",
    ariaLabel: "November and December: Year-End Lists",
    monoLabel: "— MOVEMENT III · COMMIT · NOVEMBER · DECEMBER · 2026",
    displayLine1: "Year-End Lists",
    displayLine2: "",
  },
  {
    id: "measurement",
    pageNumber: 16,
    navTitle: "Measurement",
    overlayName: "Measurement",
    overlayTitle: "What success looks like.",
    ariaLabel: "Measurement: three lenses for success",
    monoLabel: "— MEASUREMENT",
    displayLine1: "Measurement",
    displayLine2: "",
  },
  {
    id: "events-overview",
    pageNumber: 17,
    navTitle: "Events",
    overlayName: "Events · Overview",
    overlayTitle: "WhiskyFest NYC · Nov 20, 2026 · reimagined, elevated tasting, in-app experience.",
    ariaLabel: "Events overview: WhiskyFest NYC and Shanken live events",
    monoLabel: "— EVENTS · OVERVIEW",
    displayLine1: "Events",
    displayLine2: "",
  },
  {
    id: "whiskyfest-opportunities",
    pageNumber: 18,
    navTitle: "WhiskyFest · Ops",
    overlayName: "WhiskyFest NYC · Event Opportunities",
    overlayTitle: "Five sponsorship paths from presenting brand to gift bag.",
    ariaLabel: "WhiskyFest NYC: event opportunity sponsorship tiers",
    monoLabel: "— EVENT OPPORTUNITIES · WHISKYFEST NYC",
    displayLine1: "Event Opportunities",
    displayLine2: "",
  },
  {
    id: "whiskyfest-tiers",
    pageNumber: 19,
    navTitle: "WhiskyFest · 2026",
    overlayName: "WhiskyFest 2026 · Tiers + Innovations",
    overlayTitle: "Hand-to-hand with the buyer who already says yes.",
    ariaLabel: "WhiskyFest 2026 attendee tiers, sponsorship, app innovations, closed loop",
    monoLabel: "20B · WHISKYFEST 2026 · TIERS + INNOVATIONS",
    displayLine1: "WhiskyFest 2026.",
    displayLine2: "",
  },
  {
    id: "thank-you",
    pageNumber: 20,
    navTitle: "Thank You",
    overlayName: "Thank You",
    overlayTitle: "We would love to set sail with you.",
    ariaLabel: "Thank you and contact: Michael DiChiara",
    monoLabel: "— WITH GRATITUDE",
    displayLine1: "Thank you.",
    displayLine2: "",
  },
];

export const TOTAL_SLIDES = SECTIONS.length;
