export type SectionDefinition = {
  id: string;
  pageNumber: number;
  navTitle: string;
  overlayName: string;
  overlayTitle: string;
  ariaLabel: string;
  monoLabel?: string;
  displayLine1?: string;
  displayLine2?: string;
};

export const SECTIONS: SectionDefinition[] = [
  {
    id: "cover",
    pageNumber: 1,
    navTitle: "Cover",
    overlayName: "Cover",
    overlayTitle: "A Voyage of the Senses.",
    ariaLabel: "Cover: A Voyage of the Senses.",
    monoLabel: "H2 2026 · A PARTNERSHIP PROGRAM",
    displayLine1: "A Voyage",
    displayLine2: "of the Senses.",
  },
  {
    id: "intro",
    pageNumber: 2,
    navTitle: "Intro",
    overlayName: "Intro",
    overlayTitle: "The Brief",
    ariaLabel: "Intro: The Brief",
    monoLabel: "— THE BRIEF",
    displayLine1: "The Brief",
    displayLine2: "",
  },
  {
    id: "opportunity",
    pageNumber: 3,
    navTitle: "Opportunity",
    overlayName: "The Opportunity",
    overlayTitle: "The Opportunity",
    ariaLabel: "The Opportunity",
    monoLabel: "— THE OPPORTUNITY",
    displayLine1: "The Opportunity",
    displayLine2: "",
  },
  {
    id: "voyage-map",
    pageNumber: 4,
    navTitle: "Voyage Map",
    overlayName: "Voyage Map",
    overlayTitle: "Sponsored Series · 6.5 mo",
    ariaLabel: "Voyage Map: Sponsored Series, six point five months",
    monoLabel: "— THE WINDOW",
    displayLine1: "Voyage Map",
    displayLine2: "Sponsored Series · 6.5 mo",
  },
  {
    id: "transition",
    pageNumber: 5,
    navTitle: "Interlude",
    overlayName: "Interlude",
    overlayTitle: "Between Acts",
    ariaLabel: "Transition between acts",
    monoLabel: "— INTERLUDE —",
    displayLine1: "",
    displayLine2: "",
  },
  {
    id: "architecture",
    pageNumber: 6,
    navTitle: "Architecture",
    overlayName: "The Architecture",
    overlayTitle: "The Program",
    ariaLabel: "The Architecture: The Program",
    monoLabel: "— THE PROGRAM",
    displayLine1: "The Architecture",
    displayLine2: "The Program",
  },
  {
    id: "pillar-i",
    pageNumber: 7,
    navTitle: "Pillar I",
    overlayName: "Pillar I",
    overlayTitle: "Voyage Map · Always-On · Hub Residency",
    ariaLabel: "Pillar I: Voyage Map, Always-On, Hub Residency",
    monoLabel: "PILLAR I",
    displayLine1: "Voyage Map",
    displayLine2: "Always-On · Hub Residency",
  },
  {
    id: "pillar-ii",
    pageNumber: 8,
    navTitle: "Pillar II",
    overlayName: "Pillar II",
    overlayTitle: "Rare Spirits, Rare Destinations",
    ariaLabel: "Pillar II: Rare Spirits, Rare Destinations",
    monoLabel: "PILLAR II",
    displayLine1: "Rare Spirits, Rare Destinations",
    displayLine2: "Long-Form · Expert Voices · Hub Residency",
  },
  {
    id: "pillar-iii",
    pageNumber: 9,
    navTitle: "Pillar III",
    overlayName: "Pillar III",
    overlayTitle: "Dram Diaries",
    ariaLabel: "Pillar III: Dram Diaries",
    monoLabel: "PILLAR III",
    displayLine1: "Dram Diaries",
    displayLine2: "13 Social Units · 5 Weeks Of Post-Voyage",
  },
  {
    id: "the-hub",
    pageNumber: 10,
    navTitle: "The Hub",
    overlayName: "The Hub",
    overlayTitle: "SOP 100% · SOS 100%",
    ariaLabel: "The Hub: SOP one hundred percent, SOS one hundred percent",
    monoLabel: "— THE HUB",
    displayLine1: "The Hub",
    displayLine2: "SOP 100% · SOS 100%",
  },
  {
    id: "june-launch",
    pageNumber: 11,
    navTitle: "June",
    overlayName: "June · Launch",
    overlayTitle: "Set Sail. Launch Week.",
    ariaLabel: "June Launch",
    monoLabel: "JUNE · LAUNCH",
    displayLine1: "Set Sail.",
    displayLine2: "Launch Week.",
  },
  {
    id: "july-surge",
    pageNumber: 12,
    navTitle: "July",
    overlayName: "July · Surge + Sneak Peek",
    overlayTitle: "Trade Winds. Surge + Sneak Peek.",
    ariaLabel: "July Surge and Sneak Peek",
    monoLabel: "JULY · SURGE + SNEAK PEEK",
    displayLine1: "Trade Winds.",
    displayLine2: "Surge + Sneak Peek.",
  },
  {
    id: "august-prestige",
    pageNumber: 13,
    navTitle: "August",
    overlayName: "August · Prestige",
    overlayTitle: "High Tide. Prestige.",
    ariaLabel: "August Prestige",
    monoLabel: "AUGUST · PRESTIGE",
    displayLine1: "High Tide.",
    displayLine2: "Prestige.",
  },
  {
    id: "september-whiskylive",
    pageNumber: 14,
    navTitle: "September",
    overlayName: "September · WhiskyLive",
    overlayTitle: "Port of Call. WhiskyLive.",
    ariaLabel: "September WhiskyLive",
    monoLabel: "SEPTEMBER · WHISKYLIVE",
    displayLine1: "Port of Call.",
    displayLine2: "WhiskyLive.",
  },
  {
    id: "year-end-lists",
    pageNumber: 15,
    navTitle: "Year-End",
    overlayName: "Nov/Dec · Year-End Lists",
    overlayTitle: "The Reckoning. The Commitment.",
    ariaLabel: "November December Year-End Lists",
    monoLabel: "NOV/DEC · YEAR-END LISTS",
    displayLine1: "The Reckoning.",
    displayLine2: "The Commitment.",
  },
  {
    id: "measurement",
    pageNumber: 16,
    navTitle: "Measurement",
    overlayName: "Measurement",
    overlayTitle: "3 Lenses · 1 Dashboard",
    ariaLabel: "Measurement: three lenses, one dashboard",
    monoLabel: "— MEASUREMENT",
    displayLine1: "Measurement",
    displayLine2: "3 Lenses · 1 Dashboard",
  },
  {
    id: "fin",
    pageNumber: 17,
    navTitle: "Fin",
    overlayName: "Fin",
    overlayTitle: "Regent × M. Shanken",
    ariaLabel: "Fin: Regent and M. Shanken",
    monoLabel: "— REGENT × M. SHANKEN —",
    displayLine1: "Regent × M. Shanken",
    displayLine2: "",
  },
];

export const TOTAL_SLIDES = SECTIONS.length;
